Game logic
Lidya1234/Tic_tac_toe_game pull request #5
Opened 2020-10-05 14:42 UTC by Lidya1234

-Added Game and player files
-Added Game, validator, and player classes.
-Made the project to work like a tictac toe game

2020-10-05 17:09 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey @Lidya1234,  your project is looking really good, however, to accomplish as the actual project, you're required to do these changes, listed below:
 
 
## [REQUIRED CHANGES]
- [x] No puts/print and get.chomp outside `main.rb` file. ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from Pathwright)

Behaviour, like rules and moves: Couldn't be reviewed due⤵
- [x] Your game isn't working, please fix it;
![image](https://user-images.githubusercontent.com/56762529/95109417-f370e500-0712-11eb-8e20-aab70a6628c1.png)

## Summary
✨ Nice classes usage 💯
✨ Well done creating single responsibility methods ⚙
✨ Descriptive PR ✅

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-10-06 12:52 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Lidya Ghebreigzabher Okubamichael** 
Nice job the implementing the required changes :muscle:  :muscle: 
We still need to fix some issues before you can go ahead with your next challenge:

- [x] You should remove the .gitkeep file, it's not necessary anymore.
- [x] Game must show the player name when you request an action, you might replace "Enter your choice" with something like "<player_name>, enter your choice".
- [ ] Game must show the player's name when you inform that the action was invalid
- [ ] Game must show the player's name when the player has won
- [ ] Make sure the player's name has at least one character.
- [ ] When the game was a draw, replace "Game Over" with "Game was a draw" or similar

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-10-06 18:17 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey @Lidya1234,  your project is looking really good, however, to accomplish as the actual project, you're required to do these changes, listed below:
 
 
## [REQUIRED CHANGES]

- [ ] As @andresporras3423 said: When the game was a draw, replace "Game Over" with "Game was a draw" or similar.
![image](https://user-images.githubusercontent.com/56762529/95243306-d3aaf100-07e6-11eb-8be2-781a9a650a13.png)


## [OPTIONAL CHANGES] 
By opening your game.rb, and adding system "cls", you clear the terminal everytime you game is drawn, so It gets prettier
![image](https://user-images.githubusercontent.com/56762529/95243166-9ba3ae00-07e6-11eb-97db-c9d1290c197e.png)

## Summary
✨ Nice classes usage 💯
✨ Well done creating single responsibility methods ⚙
✨ Descriptive PR ✅

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-10-06 18:17 UTC, kevincappuccino commented on lib/game.rb
> +      if @board[position - 1] == ' '
Here at line 69 you can add `system ""cls"` to improve UX of your game;

2020-10-06 19:33 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-10-06 20:19 UTC, merged